"""Increase the length of the code to store custom URLs

Revision ID: 6368c8798674
Revises: c0ad691b42b5
Create Date: 2026-06-04 08:59:24.718520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6368c8798674'
down_revision: Union[str, Sequence[str], None] = 'c0ad691b42b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('short_links', 'code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=25),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('short_links', 'code',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
    # ### end Alembic commands ###
