"""add visitor_count field to the ShortLink model

Revision ID: c0ad691b42b5
Revises: e53821a46885
Create Date: 2026-06-04 08:21:55.438576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ad691b42b5'
down_revision: Union[str, Sequence[str], None] = 'e53821a46885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_links', sa.Column('visitor_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('short_links', 'visitor_count')
    # ### end Alembic commands ###
