"""create ShortLink model

Revision ID: e53821a46885
Revises: 
Create Date: 2026-06-03 20:43:42.484749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e53821a46885'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_link', sa.String(length=500), nullable=True),
    sa.Column('code', sa.String(length=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_links_code'), 'short_links', ['code'], unique=True)
    op.create_index(op.f('ix_short_links_id'), 'short_links', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_links_id'), table_name='short_links')
    op.drop_index(op.f('ix_short_links_code'), table_name='short_links')
    op.drop_table('short_links')
    # ### end Alembic commands ###
